# Generated by Django 2.2.5 on 2019-12-14 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KayitModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=60)),
                ('soyadi', models.CharField(max_length=60)),
                ('cinsiyet', models.CharField(choices=[(0, 'ERKEK'), (1, 'KADIN')], max_length=15)),
                ('tcKimlikNo', models.BigIntegerField()),
                ('kayit_zaman', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
